name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping de l'application Streamlit
        run: |
          curl -s --max-redirs 2 -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          "https://assistant-code-travail.streamlit.app" > /dev/null || true
          
          echo "✅ Visite simulée avec succès. L'application reste éveillée !"
