name: Keep Streamlit App Alive

on:
  schedule:
    # Exécution automatique tous les jours à 08h00 et 20h00 (UTC)
    - cron: '0 8,20 * * *'
  workflow_dispatch: # Permet de lancer le script manuellement depuis l'interface GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping de l'application Streamlit
        run: |
          curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          "https://assistant-code-travail.streamlit.app" > /dev/null
          
          echo "✅ Visite simulée avec succès sur https://assistant-code-travail.streamlit.app. L'application reste éveillée !"
